eidola_init/config/routes.rb
Eidola::Application.routes.draw do
  resources :news

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  resources :artists

  resources :releases do
    get :autocomplete_artist_name, :on => :collection
  end

  root :to => "news#index"

end

eidola_init/app/views/layouts/_footer.html.erb
<% content_for :footer do %>
<div id="footer">
  <div class="navbar navbar-inverse">
    <div class="navbar-inner">
      <div class="nav-collapse collapse">
	<ul class="nav dropup">
	  <a href="#" class="btn dropdown-toggle" data-toggle="dropdown">Soundcloud Player <b class="caret"></b></a>
          <ul class="dropdown-menu" style="width:400px;">
	    <% soundcloudid = 'eidolarecordcompany' if local_assigns[:soundcloudid] == "" || local_assigns[:soundcloudid].nil? %>
	    <% logger.info 'Soundcloud ID: ' << soundcloudid %>
	    <%= soundcloud(soundcloudid).html_safe %>
	  </ul>  
	</ul>
      </div>
    </div>
  </div>
</div>
<% end %>

eidola_init/app/views/layouts/_share.html.erb
<div class="g-plus" data-action="share" data-annotation="vertical-bubble" data-href="<%= Rails.application.routes.url_helpers.news_path f %>" data-height="60"></div>
<a class="twitter-share-button" data-url="<%= Rails.application.routes.url_helpers.news_path f %>" data-hashtags="eidolarecords" data-via="eidolarecords" data-lang="en" data-count="vertical">Tweet</a>
<div class="fb-like" data-href="<%= Rails.application.routes.url_helpers.news_path f %>" data-layout="box_count" data-action="like" data-show-faces="true" data-share="true"></div>

eidola_init/app/views/layouts/_side_bar.html.erb
<div class="feature">
  <div class="item">
    <%= link_to f, :title=> f.title, :class => 'white' do %>
    <h1><%= f.title %></h1>
    <%= image_tag(f.cover.url(:thumb)) %>
    <% end %>
  </div>
</div>
 

eidola_init/app/views/layouts/_soundcloud.html.erb
<div class="soundcloud collapsed">
  <%= soundcloud('eidolarecordcompany').html_safe %>
</div>

eidola_init/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EIDOLA RECORDS | <%= yield(:title) %></title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <header>
      <%= image_tag "logo_recordplayer.png", :class => "logo" %>
      <h1><%= link_to "EIDOLA RECORDS", root_path, :class => "white" %></h1>

      <ul class="nav">
	<li><%= link_to "ARTISTS", artists_path %></li>
	<li><%= link_to "RELEASES", releases_path %></li>
      </ul>

    </header>
    	    
    <div id="main" >
      <%= yield %>
    </div>
  </body>
</html>