eidola_init/config/routes.rb
Eidola::Application.routes.draw do
  resources :news

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  resources :artists

  resources :releases do
    get :autocomplete_artist_name, :on => :collection
  end

  root :to => "news#index"

end

eidola_init/app/models/artist.rb
class Artist < ActiveRecord::Base
  attr_accessible :description, :image, :name, :soundcloudid
  validates  :name, presence: true, uniqueness: true
  has_many :artist_releases
  has_many :releases, :through => :artist_releases
  has_attached_file :image, :styles => { :medium => "300x300#", :thumb => "150x150#" },
    :path => ":rails_root/public/artists/:id/:attachment/:style/:filename",
    :url => "/artists/:id/:attachment/:style/:filename"
  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]
end

eidola_init/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  skip_before_filter :authorize, only: [:index, :show]
  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.paginate(:page => params[:page], :per_page => 9).order('name asc')
    @artists_all = Artist.paginate(:page => params[:page], :per_page => 25)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @artists }
    end
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
    @artist = Artist.find(params[:id])
    @releases = Release.joins(:artists).where(["artists.name = ?", @artist.name])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @artist }
    end
  end

  # GET /artists/new
  # GET /artists/new.json
  def new
    @artist = Artist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @artist }
    end
  end

  # GET /artists/1/edit
  def edit
    @artist = Artist.find(params[:id])
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(params[:artist])

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render json: @artist, status: :created, location: @artist }
      else
        format.html { render action: "new" }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /artists/1
  # PUT /artists/1.json
  def update
    @artist = Artist.find(params[:id])

    respond_to do |format|
      if @artist.update_attributes(params[:artist])
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy

    respond_to do |format|
      format.html { redirect_to artists_url }
      format.json { head :no_content }
    end
  end
end

eidola_init/app/helpers/artists_helper.rb
module ArtistsHelper
end

eidola_init/app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label 'Soundcloud Id' %><br />
    <%= f.text_field :soundcloudid %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

eidola_init/app/views/artists/_grid.html.erb
<% f.each do |artist| %>
<div class="artist">
  <%= link_to artist, :title=> artist.name, :class => 'white' do %>
  <%= image_tag(artist.image.url(:thumb)) %>
  <h1><%= artist.name %></h1>
  <% end %>
</div>
<% end %>

eidola_init/app/views/artists/_table.html.erb
<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <td>Name</td>
      <td>Controls</td>
    <tr>
  </thead>
  <tbody>
    <% f.each do |artist| %>
    <tr>
      <td><%= artist.name %></td>
      <td>
	<%= link_to 'Edit', edit_artist_path(artist), :class => "btn" %>
	<%= button_to 'Delete', artist, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn" %>
	<%= link_to 'Show', artist, :class => "btn" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

eidola_init/app/views/artists/edit.html.erb
<h1>Editing artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

eidola_init/app/views/artists/index.html.erb
<% title "ARTISTS" %>
<h1>ARTISTS</h1>
<div id="artists">
  <% if session[:user_id] %>
  <%= render 'table', :f => @artists_all %>
  <%= link_to 'New Artist', new_artist_path, :class => "btn" %>
  <p><%= will_paginate @artists_all %></p>
  <% else %>
  <%= render 'grid', :f => @artists %>
  <p><%= will_paginate @artists %></p>
  <% end %>
</div>

eidola_init/app/views/artists/new.html.erb
<h1>New artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

eidola_init/app/views/artists/show.html.erb
<% title @artist.name %>
<p id="notice"><%= notice %></p>
<div class="releases">
  <% @releases.each do | release | %>
  <%= render 'layouts/side_bar', :f => release %>
  <% end %>
  <h1 class="rotate">RELEASES</h1>
</div>

<div id="artist">
  <h1><%= @artist.name %></h1>
  <%= image_tag(@artist.image.url(:thumb)) %>
  <p><%= markdown(@artist.description).html_safe %></p>
  <% if session[:user_id] %>
  <%= link_to 'Edit', edit_artist_path(@artist) %> |
  <% end %>
  <%= link_to 'Back', artists_path, :class => 'btn' %>
</div>