eidola_init/config/routes.rb
Eidola::Application.routes.draw do
  resources :news

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  resources :artists

  resources :releases do
    get :autocomplete_artist_name, :on => :collection
  end

  root :to => "news#index"

end

eidola_init/app/models/news.rb
class News < ActiveRecord::Base
  attr_accessible :content, :date, :title, :image
  has_attached_file :image, :styles => { :medium => "300x300#", :thumb => "200x200#" },
    :path => ":rails_root/public/news/:id/:attachment/:style/:filename",
    :url => "/news/:id/:attachment/:style/:filename"
  scope :published, lambda { {:conditions => ["date <= ?", Time.now]} }
  scope :unpublished, lambda { {:conditions => ["date > ?", Time.now]} }

  def published?
    if(date <=  Date.today)
      @p = true
    else
      @p = false
    end
    puts "[published] %s" % @p
    @p
  end
end

eidola_init/app/controllers/news_controller.rb
class NewsController < ApplicationController
  skip_before_filter :authorize, only: [:index, :show]
  # GET /news
  # GET /news.json
  def index
    @news = News.published.paginate(:page => params[:page], :per_page => 15).order('date DESC')
    @news_all = News.paginate(:page => params[:page], :per_page => 25).order('date DESC')
    @releases = Release.random(3)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1
  # GET /news/1.json
  def show
    @news = News.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/new
  # GET /news/new.json
  def new
    @news = News.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @news }
    end
  end

  # GET /news/1/edit
  def edit
    @news = News.find(params[:id])
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(params[:news])

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render json: @news, status: :created, location: @news }
      else
        format.html { render action: "new" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /news/1
  # PUT /news/1.json
  def update
    @news = News.find(params[:id])

    respond_to do |format|
      if @news.update_attributes(params[:news])
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news = News.find(params[:id])
    @news.destroy

    respond_to do |format|
      format.html { redirect_to news_index_url }
      format.json { head :no_content }
    end
  end
end

eidola_init/app/helpers/news_helper.rb
module NewsHelper
end

eidola_init/app/views/news/_form.html.erb
<%= form_for(@news) do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% @news.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

eidola_init/app/views/news/_grid.html.erb
<div class="grid">
  <% f.each do |news| %>
  <div class="news-item" itemscope itemtype="http://schema.org/Blog">
    <div class="inner">
      <p class="date"><%= l news.date, :format => "%d %b %Y" =%></p>        
      <h1 class="title" itemprop="name"><%= news.title %></h1>
      <div class="image-title-wrapper">
	<%= image_tag(news.image.url(:thumb))  %>
      </div>
      <div class="news-text summary ellipsis" itemprop="description">
	<%= markdown(news.content).html_safe %>
      </div>
    </div>
  </div>
  <% end %>
</div>
<p>
  <%= will_paginate @posts %>
</p>

eidola_init/app/views/news/_table.html.erb
<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <td>Title</td>
      <td>Publication Date</td>
      <td>Controls</td>
    <tr>
  </thead>
  <tbody>
    <% f.each do |news| %>
    <tr>
      <td><%= news.title %></td>
      <td><%= news.date %></td>
      <td>
	<%= link_to 'Edit', edit_news_path(news), :class => "btn" %>
	<%= link_to 'Destroy', news, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn" %>
	<%= link_to 'Show', news, :class => "btn" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

eidola_init/app/views/news/edit.html.erb
<h1>Editing news</h1>

<%= render 'form' %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

eidola_init/app/views/news/index.html.erb
<% title "NEWS" %>

<div id="news">
  <% if session[:user_id] %>
  <%= render 'table', :f => @news_all %>
  <%= link_to 'New News', new_news_path, :class => "btn" %>
  <% else %>
  <%= render 'grid', :f => @news %>
  <% end %>
</div>

eidola_init/app/views/news/new.html.erb
<h1>New news</h1>

<%= render 'form' %>

<%= link_to 'Back', news_index_path %>

eidola_init/app/views/news/show.html.erb
<% if @news.published? || session[:user_id] %>
<% title @news.title %>
<p id="notice"><%= notice %></p>
<div id="news">
  <div class="news-item">
    <h1><%= @news.title %></h1>    
    <div class="date"><%= l @news.date, :format => "%d %b %Y" =%></div>
    <div class="news-item-title">
      <%= image_tag(@news.image.url(:thumb)) %>
    </div>
    <div class="news-text">
      <%= markdown(@news.content).html_safe %>
    </div>
    <% if session[:user_id] %>
    <ul>
      <li><%= link_to 'Edit', edit_news_path(@news) %></li>
      <li><%= link_to 'Destroy', @news, method: :delete, data: { confirm: 'Are you sure?' } %></li>
    </ul>
    <% end %>
  </div>
</div>
</div>
<% end %>